# Generated by Django 5.1.1 on 2024-10-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Breed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "breed_name", models.CharField(
                        max_length=155, verbose_name="Breed"
                    )
                ),
                ("description", models.TextField(
                    verbose_name="Breed description"
                )
                 ),
            ],
            options={
                "verbose_name": "Breed",
                "verbose_name_plural": "Breeds",
            },
        ),
    ]
