# Generated by Django 5.1.1 on 2024-10-02 22:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("breeds", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Kitten",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Kitten name")),
                (
                    "age_year",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(50),
                        ],
                        verbose_name="Age in year",
                    ),
                ),
                (
                    "age_month",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="Age in month",
                    ),
                ),
                ("color", models.CharField(max_length=155, verbose_name="Color")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "breed",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kittens_with_breed",
                        to="breeds.breed",
                        verbose_name="Breed",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kitten",
                "verbose_name_plural": "Kittens",
            },
        ),
    ]
